Fix tests by downgrading pip to 19.3.1
Tests are failing with errors like
```
Traceback (most recent call last):
  File
  "/work/src/debian/synapse-tools/opt/venvs/synapse-tools/lib/python3.6/site-packages/pip_custom_platform/_main.py",
  line 15, in <module>
      from pip._internal.commands import get_summaries
      ImportError: cannot import name 'get_summaries'
```
because of a changed `_internals` in `pip==20.1b1`.

Let's fix that by using `pip==19.3.1`.